name: Lighthouse CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start local server (your static site must support this)
        run: |
          python3 -m http.server 8080 &
          sleep 5

      - name: Run Lighthouse CI
        run: |
          docker run --rm -v ${{ github.workspace }}:/repo -w /repo \
            treosh/lighthouse-ci:0.11.1 \
            autorun --collect.url=http://localhost:8080
