name: Lighthouse CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start static server
        run: |
          python3 -m http.server 8080 &
          sleep 5

      - name: Run Lighthouse CI
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            -w /repo \
            docker.io/lighthouseci/lighthouse-ci:latest \
            lhci autorun --collect.url=http://localhost:8080
