name: Lighthouse CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Serve site (static)
        run: |
          python3 -m http.server 8080 &
          sleep 3

      - name: Run Lighthouse CI with Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            -w /repo \
            treosh/lhci:latest \
            lhci autorun --collect.url=http://localhost:8080
